name: Build & Push docker images to ECR

on:
    workflow_dispatch:
      inputs:
            choice:
                description: 'Type yes to build and push docker image'
                required: true
                type: string
                default: ''

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-north-1

jobs:
    docker_ecr:
        runs-on: ubuntu-latest
        steps:
            - name: safety check
              run: |
                if [ "${{ github.event.inputs.choice }}" != "yes" ]; then
                echo "build and push is cancelled"
                exit 1
                fi
              working-directory: .

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set image metadata
              id: meta
              run: echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

            - name: Configure AWS credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v5
              with:
                role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc-role
                aws-region: ${{ env.AWS_REGION }}

            - name: Login to ECR
              run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

            - name: Build docker image
              run: docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY_NAME }}:${{ steps.meta.outputs.tag }} ./gatus

            - name: Scan image
              uses: anchore/scan-action@v7
              with:
                image: '${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY_NAME }}:${{ steps.meta.outputs.tag }}'
                fail-build: false
                severity-cutoff: medium
                output-format: table

            - name: Push docker image
              run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY_NAME }}:${{ steps.meta.outputs.tag }}

            - name: Store image tag in SSM
              run: aws ssm put-parameter --name "/gatus/image-tag" --value "${{ steps.meta.outputs.tag }}" --type "String" --region ${{ env.AWS_REGION }} --overwrite